spring:
  datasource:
    username: root
    password: 123
#    //数据库时区报错
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



#      # 以下是正式环境druid连接池配置
#      initial-size: 10
#      min-idle: 10
#      max-active: 30
#      max-wait: 60000
#      time-between-eviction-runs-millis: 80000
#      min-evictable-idle-time-millis: 300000
#      max-evictable-idle-time-millis: 600000
#      validation-query: SELECT 'x' FROM DUAL
#      validation-query-timeout: 10000
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 50
#      remove-abandoned: true         # 是否自动回收超时连接
#      remove-abandoned-timeout: 60  # 超时时间(以秒数为单位)