################### 端口+上下文 ###################
server:
  port: 8000
  context-path: /
  display-name: 国家企业信用信息公示系统(河南)--正式
  compression:
    enabled: true
  tomcat:
    max-connections: 2500
    max-threads: 1000
    max-http-header-size: 8192

################### Log4j2配置 ###################
logging:
  config: classpath:log4j2/log4j2-prod.yml

################### spring配置 ###################
spring:
  output:
    ansi:
      enabled: DETECT
  http:
    multipart:
      max-request-size: 50MB     # 最大请求大小
      max-file-size: 50MB        # 最大文件大小
      file-size-threshold: 2048KB
      location: /upload/

  datasource:
    #浪潮库
    druid:
      url: jdbc:oracle:thin:@//10.8.0.17:1521/gx
      username: AP_SBDZ
      password: AP_SBDZ_1903041130
      driver-class-name: oracle.jdbc.driver.OracleDriver
      # 以下是druid连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 80000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 10000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true         # 是否自动回收超时连接
      remove-abandoned-timeout: 60  # 超时时间(以秒数为单位)
      # 智容库
    zrdb:
      url: jdbc:oracle:thin:@//10.12.3.148:1521/jsxt
      username: shibo
      password: shibo0921
      driver-class-name: oracle.jdbc.driver.OracleDriver
      # 以下是druid连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 80000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 10000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true         # 是否自动回收超时连接
      remove-abandoned-timeout: 60  # 超时时间(以秒数为单位)

    # 年报控制库
    andata:
      url: jdbc:oracle:thin:@//10.8.0.125:1521/nbsjk
      username: nbkzk
      password: nbkzk
      driver-class-name: oracle.jdbc.driver.OracleDriver
      # 以下是druid连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 80000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      validation-query: SELECT 'x' FROM DUAL
      validation-query-timeout: 10000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true         # 是否自动回收超时连接
      remove-abandoned-timeout: 60  # 超时时间(以秒数为单位)
    # mongodb
    mongodb:
      casedata:  #行政处罚
        host: 10.8.0.45
        port: 25221
        database: casefile
        userName: AP_SBDZ
        passWord: AP_SBDZ_1903041130
        min-connections-per-host: 10
        max-connections-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idel-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
        authentication-database: testDb

      tmdata:  #商标信息
        host: 10.8.0.45
        port: 25221
        database: tmfile
        userName: AP_SBDZ
        passWord: AP_SBDZ_1903041130
        min-connections-per-host: 10
        max-connections-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 120000
        max-connection-idel-time: 0
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15
        authentication-database: testDb
  aop:
    proxy-target-class: true

  redis:
    password: 123456
    cluster-nodes: 192.168.0.21:6380,192.168.0.21:6381,192.168.0.21:6382,192.168.0.22:6380,192.168.0.22:6381,192.168.0.22:6382
    expire-seconds: 120     #键的过期时间(秒)
    so-timeout: 1000        #读取数据超时时间
    max-attempts: 3         #出现异常最大重试次数
    timeout: 10000
    pool:
      max-active: 5000  #最大连接数
      max-idle: 30      #最大空闲连接数
      min-idle: 5       #最小空闲连接数
      max-wait: 3000    #获取连接最大等待时间 ms  #default -1



################### sessionFactory ###################
sessionFactory:
  packages-to-scan: com.asb.gsxt.module
  dialect: org.hibernate.dialect.Oracle10gDialect
  show-sql: false
  format-sql: false
  jdbc-batch-size: 1000
  current-session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
  # ehcache
  use-second-level-cache: true
  use-query-cache: true
  cache-region-factory-class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  cache-region-prefix: hibernate
  generate-statistics: false
  use-structured-entries: false
  provider-configuration-file-resource-path: ehcache.xml
andatasessionFactory:
  packages-to-scan: com.asb.gsxt.nbkzk.module
  dialect: org.hibernate.dialect.Oracle10gDialect
  show-sql: false
  format-sql: true
  hbm2ddl-auto: none
  jdbc-batch-size: 100
  current-session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
  # ehcache
  use-second-level-cache: true
  use-query-cache: true
  cache-region-factory-class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  cache-region-prefix: hibernate
  generate-statistics: false
  use-structured-entries: false
  provider-configuration-file-resource-path: ehcache.xml
zrdbsessionFactory:
  packages-to-scan: com.asb.gsxt.zrdb.module
  dialect: org.hibernate.dialect.Oracle10gDialect
  show-sql: true
  format-sql: true
  hbm2ddl-auto: none
  jdbc-batch-size: 100
  current-session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
  # ehcache
  use-second-level-cache: false
  use-query-cache: false
  cache-region-factory-class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  cache-region-prefix: hibernate
  generate-statistics: false
  use-structured-entries: false
  provider-configuration-file-resource-path: ehcache.xml
################### Id生成器 ###################
idWorker:
  worker-id: 0
  datacenter-id: 0

################### 一些开关配置 ###################
switch:
  interceptor: true

################### 一些系统配置 ###################
system:
  files-root: http://gsxt2.haaic.gov.cn
  icons-server-url: ${system.files-root}/icon     # icons server url
  nav-server-url: ${system.files-root}/app_images # app启动时领航页+技术支持页面图片地址
  primary-db-schema: ${spring.datasource.druid.username}   # 标准库schema
  an-db-schema: ${spring.datasource.andata.username}       # 年报库schema
  zr-db-schema: sjtbk                                      # 智容库schema

  ftp-http-server-url: ${system.files-root}/           # ftp转http
  ftp-host: 192.168.0.24                               # ftp服务器IP
  ftp-port: 21                                         # ftp服务器端口
  ftp-user: xftpadmin                                  # ftp服务器用户名
  ftp-pwd: 123456                                      # ftp服务器密码
  ftp-path-notice: scfiles                             # 简易注销文件上层目录
  ftp-case-doc: casefiles                              # 行政处罚文件上层目录
  ftp-path-base: tmfiles                               # 商标基本信息文件上层目录
  ftp-path-feedback: feedback                          # 意见反馈图片目录
  ftp-path-noticeinfo: noticeinfo                      # 公告信息
  ftp-path-objection: objectionAccept                  # 经营异常异议
  ftp-path-out: outAccept                              # 经营异常移出
  http-path-template: nbws                             # 模板下载目录
  template-suffix: .doc                                # 模板下载后缀
  auth-url: http://172.24.1.173:8001/api/v1/qrCheck    # 电子营业执照登录请求报文
  ca-login-url: http://172.24.1.173:8001/api/v1/svsCa  # CA登录请求报文
  sms-url: http://172.24.1.173:8001/api/v1/sendSMS     # 短信服务器地址
  sms-login-valid-time: 8                              # 登录短信验证码有效时间(分钟)
  ########## 本地内网文件系统地址 ##############
  lan-file-system-host: 192.168.0.24:8000
  ########## 智容ftp配置 ##############
  # ftp转http(下载文件使用)
  zr-ftp-http-server-url: ${system.files-root}/gsxtfiles/
  # ip
  zr-ftp-host: 10.8.1.64
  # 端口
  zr-ftp-port: 21
  # 用户名
  zr-ftp-user: "asbftp_gsxtfiles"
  # 密码
  zr-ftp-pwd: "asbftp_gsxtfiles"
  # 经营异常异议文件目录
  zr-ftp-path-objection: /
  # 经营异常移出文件目录
  zr-ftp-path-out: /
  zr-opinion-ftp-user: "asbftp_from_ywgl"                   #意见反馈ftp用户名
  zr-opinion-ftp-pwd: "asbftp_from_ywgl321"                 #意见反馈ftp密码
  zr-opinion-ftp-path: /
  ########## 智容ftp配置end ##############
  year-start-qy: 2013   # 企业年报填报开始年份
  year-start-nz: 2014  # 农专年报填报开始年份
  year-start-gt: 2013  # 个体年报填报开始年份
  ######### 集团成员接口地址 ##############
  group-number-domain: http://172.16.13.10:9999
  group-number-suffix: /api/EnterQuery/EntIndexInfoByCon
  group-number-app-key: henan_api
  group-number-secret-key: henan$1442
  ##############营业执照作废声明签名密钥######################
  license-nullify-key: 789LICE36gsT45FDG724gSENUL6R
  ###############企业、农专、个体年报截止时间#####################
  report-month-end-qy: 6
  report-month-end-nz: 6
  report-month-end-gt: 12
  report-day-end-qy: 30
  report-day-end-nz: 30
  report-day-end-gt: 31
  ##############校验年报信息标识##################
