var entreginfo={
	 REGID:'',//注册ID
   ANCHEID:'',//年报ID
   ENFULLCO:'',//英文名称
   ENADDRCO:'',//英文地址
   ACCOBANKNM:'',//开户银行
   ACCONO:'',//开户账号
   SPECIALTRADEZONE:'',//特殊贸易区域(CW11)
   APANAGEREGION:'',//经济区划(CW12)
   CUSSPENAME:'',//关务负责人
   CUSSPECERTYPE:'',//关务负责人身份证件类型(CB16)
   CUSSPECERNO:'',//关务负责人身份证件号码
   CUSSPETEL:'',//关务负责人固定电话
   CUSSPEMOBILE:'',//关务负责人移动电话
   CUSSPEEMAIL:'',//关务负责人电子邮箱
   CONTACNAME:'',//海关业务联系人
   CONTACTTEL:'',//海关业务联系人固定电话
   CONTACTMOBILE:'',//海关业务联系人移动电话
   CONTACTEMAIL:'',//海关业务联系人电子邮箱
   CONTACTFAX:'',//海关业务联系人传真
   SITEFLAG:'',//经营场所性质(CW13)
   ACCOUNTFLAG:'',//是否实行会计电算化
   FINSOFT:'',//财务管理软件名称
   ACCOUNTTYPE:'',//记账方式(CW14)
   ACCOUNTNAME:'',//委托代理记账单位名称
   ACCOUNTSOCIALCREDITCODE:'',//委托代理记账单位统一社会信用代码
   ACCOUNTADDR:'',//委托代理记账单位地址
   ACCOUNTCONTACT:'',//委托代理记账单位联系人
   ACCOUNTTEL:'',//委托代理记账单位联系人电话
   SUSTAINEDLOSSES:'',//最近三年是否连续亏损
   GOODSINSTOCK:0,//存货（万元）
   CASHLIABILITY:0,//流动负债（万元）
   CIRCULATINGASSETS:0,//流动资产（万元）
   NETCASHFLOW:0,//经营现金净流量（万元）
   OPERATINGPROFIT:0,//营业利润（万元）
   OWNERSEQUITY:0,//年初所有者权益（万元）
   ISAUDITED:'',//年度内是否开展内外部审计
   EXISTINGPROBLEMS:'',//在内外部审计等企业自律管理中，是否发现一般贸易业务、加工贸易及保税业务、减免税业务或其他进出口业务存在违反海关管理规定的问题。
   PROBLEMS:'',//具体问题
   HASTAXRELIEFGOODS:'',//是否有海关减免税监管货物
   INSTALLLOCATION:'',//减免税进口货物安装地点、使用情况
   HANDLINGSITUATION:'',//减免税进口货物调换、抵押、质押、留置、转让、出售、移作他用、退运境外或进行其他处置的情事
   ILLEGALUSED:'',//减免税进口货物未按照特定用途、特定地区、特定企业使用的情事
   THESAMEASDECLARE:'',//实际进口的减免税货物的规格、型号和技术参数是，否与申报减免税申请）时相同
   RECAPITALISE:'',//减免税申请人改制、股权转让、合并、分立及其他资产重组情况
   ISFIXEDASSETS:'',//减免税进口货物是否已入本单位固定资产账
   OTHERMATTERS:'',//其他需要向海关说明的情况
   S_EXT_FROMNODE:'',//数据汇总单位
   S_EXT_DATATIME:null,//数据汇总时间
   ANCHEIS:2,//公示状态，1公示，2未公示
   XJBS:1,   //新旧标识
   fauditJson:null
}
